export const continents = [
  {
    id: "north-america",
    name: "North America",
    subtitle: "From towering mountains to vibrant cities.",
    countries: 3,
    image: "/images/hero/continents/north-america.png",
    href: "/north-america",
  },
  {
    id: "europe",
    name: "Europe",
    subtitle: "Centuries of history, culture and unforgettable cuisine.",
    countries: 14,
    image: "/images/hero/continents/europe.png",
    href: "/europe",
  },
  {
    id: "asia",
    name: "Asia",
    subtitle: "Ancient traditions meet modern wonders.",
    countries: 9,
    image: "/images/hero/continents/asia.png",
    href: "/asia",
  },
  {
    id: "africa",
    name: "Africa",
    subtitle: "Wild landscapes and unforgettable safaris.",
    countries: 5,
    image: "/images/hero/continents/africa.png",
    href: "/africa",
  },
  {
    id: "oceania",
    name: "Oceania",
    subtitle: "Paradise islands and endless coastlines.",
    countries: 2,
    image: "/images/hero/continents/oceania.png",
    href: "/oceania",
  },
  {
    id: "south-america",
    name: "South America",
    subtitle: "The next great adventure awaits.",
    countries: 0,
    image: "/images/hero/continents/south-america.png",
    href: "/south-america",
  },
];