export const europeCountries = [
  {
    id: "france",
    name: "France",
    flag: "🇫🇷",
    isoCode: "FR",
  },
  {
    id: "monaco",
    name: "Monaco",
    flag: "🇲🇨",
    isoCode: "MC",
  },
  {
    id: "italy",
    name: "Italy",
    flag: "🇮🇹",
    isoCode: "IT",
  },
  {
    id: "england",
    name: "England",
    flag: "🇬🇧",
    isoCode: "GB",
  },
  {
    id: "netherlands",
    name: "Netherlands",
    flag: "🇳🇱",
    isoCode: "NL",
  },
  {
    id: "spain",
    name: "Spain",
    flag: "🇪🇸",
    isoCode: "ES",
  },
  {
    id: "portugal",
    name: "Portugal",
    flag: "🇵🇹",
    isoCode: "PT",
  },
  {
    id: "greece",
    name: "Greece",
    flag: "🇬🇷",
    isoCode: "GR",
  },
  {
    id: "croatia",
    name: "Croatia",
    flag: "🇭🇷",
    isoCode: "HR",
  },
  {
    id: "montenegro",
    name: "Montenegro",
    flag: "🇲🇪",
    isoCode: "ME",
  },
  {
    id: "switzerland",
    name: "Switzerland",
    flag: "🇨🇭",
    isoCode: "CH",
  },
  {
    id: "sweden",
    name: "Sweden",
    flag: "🇸🇪",
    isoCode: "SE",
  },
  {
    id: "denmark",
    name: "Denmark",
    flag: "🇩🇰",
    isoCode: "DK",
  },
  {
    id: "turkey",
    name: "Turkey",
    flag: "🇹🇷",
    isoCode: "TR",
  },
];